name: Docker Build/Test
on:
  workflow_call: {}
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
permissions:
  contents: read
jobs:
  test:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        run: make init static-analysis build test
